### ISSUE TITLE
normalize.scss obsolete?

### ISSUE THREAD

**Issue by David-van-den-Bor** [JeremyEnglert/JointsWP#153]
Hi Jeremy!

Just a question: What was the reason for including the *normalize.scss* file? Hasn't the way Foundation 6 deals with normalizing css changed? If you "bower foundation" you'll see the normalize file is missing from the standard dependencies install. I also read in the changelog that Foundation 6.0.6 has moved the "normalization" to *_global.scss* (bundled with the foundation-global-styles() mixin) If that's the case, could it be possible to just leave out the vendor *normalize.scss* file? One less import to worry about :-)

For instance, I compared both your vendor *normalize.scss* and the native foundation *_global.scss* (imported by *foundation.scss*) with each other. Take a look at the bottom of both files: they contain exactly the same code for normalizing tables:

https://github.com/JeremyEnglert/JointsWP/blob/master/vendor/foundation-sites/scss/vendor/normalize.scss 

```scss
/* Tables
   ========================================================================== */

/**
 * Remove most spacing between table cells.
 */

table {
  border-collapse: collapse;
  border-spacing: 0;
}

td,
th {
  padding: 0;
}
```

https://github.com/JeremyEnglert/JointsWP/blob/master/vendor/foundation-sites/scss/_global.scss

```scss
  /* Tables
     ========================================================================== */

  /**
   * Remove most spacing between table cells.
   */

  table {
    border-collapse: collapse;
    border-spacing: 0;
  }

  td,
  th {
    padding: 0;
  }
}
```
